[package]
name = "injectum_classic"
version = "0.1.0"
authors = ["Skyn√µx <0x536b796ec3b578@proton.me>"]
edition = "2024"
repository = "https://github.com/0x536b796ec3b578/injectum"
license = "MIT"

[dependencies]
windows.workspace = true
